name: Build and Release Arduino Sketch

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1
      
    - name: Install Arduino CLI
      run: |
        arduino-cli core update-index
        arduino-cli core install rp2040:rp2040
        
    - name: Install required libraries
      run: |
        arduino-cli lib install "ArduinoJson"
        arduino-cli lib install "LittleFS_Mbed_RP2040"
        
    - name: Configure Arduino CLI
      run: |
        arduino-cli config init
        arduino-cli core update-index
        
    - name: Verify sketch compiles
      run: |
        arduino-cli compile --fqbn rp2040:rp2040:rpipicow pico_ota_updater/pico_ota_updater.ino
        
    - name: Build firmware
      run: |
        arduino-cli compile --fqbn rp2040:rp2040:rpipicow --output-dir ./build pico_ota_updater/pico_ota_updater.ino
        
    - name: List build files
      run: |
        ls -la ./build/
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Automated release of Pico W firmware
          
          **Installation:**
          1. Download the .bin file
          2. The Pico W will automatically detect and install this update if OTA is enabled
          
          **Changes:**
          - See commit history for detailed changes
        draft: false
        prerelease: false
        
    - name: Upload firmware binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/pico_ota_updater.ino.bin
        asset_name: pico_firmware.bin
        asset_content_type: application/octet-stream
        
    - name: Upload UF2 file (if available)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/pico_ota_updater.ino.uf2
        asset_name: pico_firmware.uf2
        asset_content_type: application/octet-stream
      continue-on-error: true  # UF2 might not be generated for all builds
